name: shoorah_test_app
description: "Flutter Shoorah App for assignment"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.2.0+3
  equatable: ^2.0.5
  http: ^1.1.0
  flutter_bloc: ^8.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
